<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Joovlly\Authorizable\Models\Role;

class RolesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        Role::create([
            'name' => 'Administrator',
            'slug' => 'admin',
            'permissions' => [
                'store-discount' => true,
                'create-discount' => true,
                'edit-discount' => true,
                'show-discount' => true,
                'destroy-discount' => true,
                'index-discount' => true,
                'update-discount' => true,

                'store-reservation' => true,
                'create-reservation' => true,
                'edit-reservation' => true,
                'show-reservation' => true,
                'destroy-reservation' => true,
                'index-reservation' => true,
                'update-reservation' => true,

                'store-accommodation' => true,
                'create-accommodation' => true,
                'edit-accommodation' => true,
                'show-accommodation' => true,
                'destroy-accommodation' => true,
                'index-accommodation' => true,
                'update-accommodation' => true,

                'store-contract' => true,
                'create-contract' => true,
                'edit-contract' => true,
                'show-contract' => true,
                'destroy-contract' => true,
                'index-contract' => true,
                'update-contract' => true,

                'store-template' => true,
                'create-template' => true,
                'edit-template' => true,
                'show-template' => true,
                'destroy-template' => true,
                'index-template' => true,
                'update-template' => true,

                'store-album' => true,
                'create-album' => true,
                'edit-album' => true,
                'show-album' => true,
                'destroy-album' => true,
                'index-album' => true,
                'update-album' => true,

                'store-branch' => true,
                'create-branch' => true,
                'edit-branch' => true,
                'show-branch' => true,
                'destroy-branch' => true,
                'index-branch' => true,
                'update-branch' => true,

                'store-branch_shift' => true,
                'show-branch_shift' => true,
                'edit-branch_shift' => true,
                'create-branch_shift' => true,
                'index-branch_shift' => true,
                'update-branch_shift' => true,
                'destroy-branch_shift' => true,

                'store-ingredient' => true,
                'create-ingredient' => true,
                'edit-ingredient' => true,
                'show-ingredient' => true,
                'destroy-ingredient' => true,
                'index-ingredient' => true,
                'update-ingredient' => true,

                'store-stock' => true,
                'create-stock' => true,
                'edit-stock' => true,
                'show-stock' => true,
                'destroy-stock' => true,
                'index-stock' => true,
                'update-stock' => true,

                'store-address' => true,
                'show-address' => true,
                'destroy-address' => true,
                'index-address' => true,
                'update-address' => true,
                'edit-address' => true,
                'create-address' => true,

                'store-user_order' => true,
                'show-user_order' => true,
                'edit-user_order' => true,
                'create-user_order' => true,
                'index-user_order' => true,
                'update-user_order' => true,
                'destroy-user_order' => true,

                'store-order' => true,
                'create-order' => true,
                'edit-order' => true,
                'show-order' => true,
                'destroy-order' => true,
                'index-order' => true,
                'update-order' => true,

                'store-post' => true,
                'index-post' => true,
                'create-post' => true,
                'edit-post' => true,
                'show-post' => true,
                'update-post' => true,
                'destroy-post' => true,
                'approve-post' => true,

                'store-location' => true,
                'create-location' => true,
                'edit-location' => true,
                'index-location' => true,
                'show-location' => true,
                'update-location' => true,
                'destroy-location' => true,

                'store-product' => true,
                'create-product' => true,
                'edit-product' => true,
                'index-product' => true,
                'show-product' => true,
                'update-product' => true,
                'destroy-product' => true,

                'index-product_variation' => true,
                'create-product_variation' => true,
                'edit-product_variation' => true,
                'show-product_variation' => true,
                'update-product_variation' => true,
                'store-product_variation' => true,
                'destroy-product_variation' => true,

                'index-product_variation_type' => true,
                'create-product_variation_type' => true,
                'edit-product_variation_type' => true,
                'show-product_variation_type' => true,
                'update-product_variation_type' => true,
                'store-product_variation_type' => true,
                'destroy-product_variation_type' => true,

                'store-category' => true,
                'edit-category' => true,
                'create-category' => true,
                'show-category' => true,
                'update-category' => true,
                'destroy-category' => true,

                'store-review' => true,
                'destroy-review' => true,
                'update-review' => true,

                'store-comment' => true,
                'update-comment' => true,
                'show-comment' => true,
                'destroy-comment' => true,

                'store-user' => true,
                'fastUser-store' => true,
                'fastAddress-store' => true,
                'create-user' => true,
                'edit-user' => true,
                'show-user' => true,
                'destroy-user' => true,
                'index-user' => true,
                'update-user' => true,

                'index-notification' => true,
                'update-notification' => true,

            ],
        ]);
        Role::create([
            'name' => 'Delivery Guy',
            'slug' => 'delivery',
            'permissions' => [
                'store-discount' => true,
                'create-discount' => true,
                'edit-discount' => true,
                'show-discount' => true,
                'destroy-discount' => true,
                'index-discount' => true,
                'update-discount' => true,

                'store-reservation' => true,
                'create-reservation' => true,
                'edit-reservation' => true,
                'show-reservation' => true,
                'destroy-reservation' => true,
                'index-reservation' => true,
                'update-reservation' => true,

                'store-accommodation' => true,
                'create-accommodation' => true,
                'edit-accommodation' => true,
                'show-accommodation' => true,
                'destroy-accommodation' => true,
                'index-accommodation' => true,
                'update-accommodation' => true,

                'store-contract' => true,
                'create-contract' => true,
                'edit-contract' => true,
                'show-contract' => true,
                'destroy-contract' => true,
                'index-contract' => true,
                'update-contract' => true,

                'store-branch' => true,
                'create-branch' => true,
                'edit-branch' => true,
                'show-branch' => true,
                'destroy-branch' => true,
                'index-branch' => true,
                'update-branch' => true,

                'store-ingredient' => true,
                'create-ingredient' => true,
                'edit-ingredient' => true,
                'show-ingredient' => true,
                'destroy-ingredient' => true,
                'index-ingredient' => true,
                'update-ingredient' => true,

                'store-stock' => true,
                'create-stock' => true,
                'edit-stock' => true,
                'show-stock' => true,
                'destroy-stock' => true,
                'index-stock' => true,
                'update-stock' => true,

                'store-address' => true,
                'show-address' => true,
                'destroy-address' => true,
                'index-address' => true,
                'update-address' => true,
                'edit-address' => true,
                'create-address' => true,

                'store-user_order' => true,
                'show-user_order' => true,
                'edit-user_order' => true,
                'create-user_order' => true,
                'index-user_order' => true,
                'update-user_order' => true,
                'destroy-user_order' => true,

                'store-order' => true,
                'create-order' => true,
                'edit-order' => true,
                'show-order' => true,
                'destroy-order' => true,
                'index-order' => true,
                'update-order' => true,

                'store-post' => true,
                'index-post' => true,
                'create-post' => true,
                'edit-post' => true,
                'show-post' => true,
                'update-post' => true,
                'destroy-post' => true,
                'approve-post' => true,

                'store-location' => true,
                'create-location' => true,
                'edit-location' => true,
                'index-location' => true,
                'show-location' => true,
                'update-location' => true,
                'destroy-location' => true,

                'store-product' => true,
                'create-product' => true,
                'edit-product' => true,
                'index-product' => true,
                'show-product' => true,
                'update-product' => true,
                'destroy-product' => true,

                'index-product_variation' => true,
                'create-product_variation' => true,
                'edit-product_variation' => true,
                'show-product_variation' => true,
                'update-product_variation' => true,
                'store-product_variation' => true,
                'destroy-product_variation' => true,

                'index-product_variation_type' => true,
                'create-product_variation_type' => true,
                'edit-product_variation_type' => true,
                'show-product_variation_type' => true,
                'update-product_variation_type' => true,
                'store-product_variation_type' => true,
                'destroy-product_variation_type' => true,

                'store-category' => true,
                'edit-category' => true,
                'create-category' => true,
                'show-category' => true,
                'update-category' => true,
                'destroy-category' => true,

                'store-review' => true,
                'destroy-review' => true,
                'update-review' => true,

                'store-comment' => true,
                'update-comment' => true,
                'show-comment' => true,
                'destroy-comment' => true,

                'store-user' => true,
                'create-user' => true,
                'edit-user' => true,
                'show-user' => true,
                'destroy-user' => true,
                'index-user' => true,
                'update-user' => true,

                'index-notification' => true,
                'update-notification' => true,

            ],
        ]);
        Role::create([
            'name' => 'Call Center',
            'slug' => 'call-center',
            //order,reservations
            'permissions' => [
                'store-discount' => false,
                'create-discount' => false,
                'edit-discount' => false,
                'show-discount' => false,
                'destroy-discount' => false,
                'index-discount' => false,
                'update-discount' => false,

                'store-reservation' => true,
                'create-reservation' => true,
                'edit-reservation' => true,
                'show-reservation' => true,
                'destroy-reservation' => false,
                'index-reservation' => false,
                'update-reservation' => true,

                'store-accommodation' => false,
                'create-accommodation' => false,
                'edit-accommodation' => false,
                'show-accommodation' => false,
                'destroy-accommodation' => false,
                'index-accommodation' => false,
                'update-accommodation' => false,

                'store-branch' => false,
                'create-branch' => false,
                'edit-branch' => false,
                'show-branch' => true,
                'destroy-branch' => false,
                'index-branch' => true,
                'update-branch' => false,

                'store-ingredient' => false,
                'create-ingredient' => false,
                'edit-ingredient' => false,
                'show-ingredient' => true,
                'destroy-ingredient' => false,
                'index-ingredient' => true,
                'update-ingredient' => false,

                'store-stock' => false,
                'create-stock' => false,
                'edit-stock' => false,
                'show-stock' => false,
                'destroy-stock' => false,
                'index-stock' => false,
                'update-stock' => false,

                'store-address' => true,
                'show-address' => true,
                'destroy-address' => true,
                'index-address' => true,
                'update-address' => true,
                'edit-address' => true,
                'create-address' => true,

                'store-user_order' => true,
                'show-user_order' => true,
                'edit-user_order' => true,
                'create-user_order' => true,
                'index-user_order' => true,
                'update-user_order' => true,
                'destroy-user_order' => false,

                'store-order' => false,
                'create-order' => false,
                'edit-order' => false,
                'show-order' => false,
                'destroy-order' => false,
                'index-order' => false,
                'update-order' => false,

                'store-post' => false,
                'index-post' => true,
                'create-post' => false,
                'edit-post' => false,
                'show-post' => true,
                'update-post' => false,
                'destroy-post' => false,
                'approve-post' => false,

                'store-location' => false,
                'create-location' => false,
                'edit-location' => false,
                'index-location' => true,
                'show-location' => true,
                'update-location' => false,
                'destroy-location' => false,

                'store-product' => false,
                'create-product' => false,
                'edit-product' => false,
                'index-product' => true,
                'show-product' => true,
                'update-product' => false,
                'destroy-product' => false,

                'index-product_variation' => true,
                'create-product_variation' => false,
                'edit-product_variation' => true,
                'show-product_variation' => false,
                'update-product_variation' => false,
                'store-product_variation' => false,
                'destroy-product_variation' => false,

                'index-product_variation_type' => false,
                'create-product_variation_type' => false,
                'edit-product_variation_type' => false,
                'show-product_variation_type' => false,
                'update-product_variation_type' => false,
                'store-product_variation_type' => false,
                'destroy-product_variation_type' => false,

                'store-category' => false,
                'edit-category' => false,
                'create-category' => false,
                'show-category' => true,
                'update-category' => false,
                'destroy-category' => false,

                'store-review' => true,
                'destroy-review' => true,
                'update-review' => true,

                'store-comment' => true,
                'update-comment' => true,
                'show-comment' => true,
                'destroy-comment' => true,

                'store-user' => false,
                'create-user' => false,
                'edit-user' => false,
                'show-user' => false,
                'destroy-user' => false,
                'index-user' => false,
                'update-user' => false,

                'index-notification' => true,
                'update-notification' => true,

            ],
        ]);
        Role::create([
            //order, reservations, assign delivery
            'name' => 'Branch Manager',
            'slug' => 'branch-manager',
            'permissions' => [
                'store-discount' => false,
                'create-discount' => false,
                'edit-discount' => false,
                'show-discount' => false,
                'destroy-discount' => false,
                'index-discount' => false,
                'update-discount' => false,

                'store-reservation' => true,
                'create-reservation' => true,
                'edit-reservation' => true,
                'show-reservation' => true,
                'destroy-reservation' => false,
                'index-reservation' => false,
                'update-reservation' => true,

                'store-accommodation' => false,
                'create-accommodation' => false,
                'edit-accommodation' => false,
                'show-accommodation' => false,
                'destroy-accommodation' => false,
                'index-accommodation' => false,
                'update-accommodation' => false,

                'store-branch' => false,
                'create-branch' => false,
                'edit-branch' => false,
                'show-branch' => true,
                'destroy-branch' => false,
                'index-branch' => true,
                'update-branch' => false,

                'store-ingredient' => false,
                'create-ingredient' => false,
                'edit-ingredient' => false,
                'show-ingredient' => true,
                'destroy-ingredient' => false,
                'index-ingredient' => true,
                'update-ingredient' => false,

                'store-stock' => false,
                'create-stock' => false,
                'edit-stock' => false,
                'show-stock' => false,
                'destroy-stock' => false,
                'index-stock' => false,
                'update-stock' => false,

                'store-address' => true,
                'show-address' => true,
                'destroy-address' => true,
                'index-address' => true,
                'update-address' => true,
                'edit-address' => true,
                'create-address' => true,

                'store-user_order' => true,
                'show-user_order' => true,
                'edit-user_order' => true,
                'create-user_order' => true,
                'index-user_order' => true,
                'update-user_order' => true,
                'destroy-user_order' => false,

                'store-order' => false,
                'create-order' => false,
                'edit-order' => false,
                'show-order' => false,
                'destroy-order' => false,
                'index-order' => false,
                'update-order' => false,

                'store-post' => false,
                'index-post' => true,
                'create-post' => false,
                'edit-post' => false,
                'show-post' => true,
                'update-post' => false,
                'destroy-post' => false,
                'approve-post' => false,

                'store-location' => false,
                'create-location' => false,
                'edit-location' => false,
                'index-location' => true,
                'show-location' => true,
                'update-location' => false,
                'destroy-location' => false,

                'store-product' => false,
                'create-product' => false,
                'edit-product' => false,
                'index-product' => true,
                'show-product' => true,
                'update-product' => false,
                'destroy-product' => false,

                'index-product_variation' => true,
                'create-product_variation' => false,
                'edit-product_variation' => true,
                'show-product_variation' => false,
                'update-product_variation' => false,
                'store-product_variation' => false,
                'destroy-product_variation' => false,

                'index-product_variation_type' => false,
                'create-product_variation_type' => false,
                'edit-product_variation_type' => false,
                'show-product_variation_type' => false,
                'update-product_variation_type' => false,
                'store-product_variation_type' => false,
                'destroy-product_variation_type' => false,

                'store-category' => false,
                'edit-category' => false,
                'create-category' => false,
                'show-category' => true,
                'update-category' => false,
                'destroy-category' => false,

                'store-review' => true,
                'destroy-review' => true,
                'update-review' => true,

                'store-comment' => true,
                'update-comment' => true,
                'show-comment' => true,
                'destroy-comment' => true,

                'store-user' => false,
                'create-user' => false,
                'edit-user' => false,
                'show-user' => false,
                'destroy-user' => false,
                'index-user' => false,
                'update-user' => false,

                'index-notification' => true,
                'update-notification' => true,

            ],
        ]);
        Role::create([
            'name' => 'User',
            'slug' => 'user',
            'permissions' => [
                'store-discount' => false,
                'create-discount' => false,
                'edit-discount' => false,
                'show-discount' => false,
                'destroy-discount' => false,
                'index-discount' => false,
                'update-discount' => false,

                'store-reservation' => true,
                'create-reservation' => true,
                'edit-reservation' => true,
                'show-reservation' => true,
                'destroy-reservation' => false,
                'index-reservation' => false,
                'update-reservation' => true,

                'store-accommodation' => false,
                'create-accommodation' => false,
                'edit-accommodation' => false,
                'show-accommodation' => false,
                'destroy-accommodation' => false,
                'index-accommodation' => false,
                'update-accommodation' => false,

                'store-branch' => false,
                'create-branch' => false,
                'edit-branch' => false,
                'show-branch' => true,
                'destroy-branch' => false,
                'index-branch' => true,
                'update-branch' => false,

                'store-ingredient' => false,
                'create-ingredient' => false,
                'edit-ingredient' => false,
                'show-ingredient' => true,
                'destroy-ingredient' => false,
                'index-ingredient' => true,
                'update-ingredient' => false,

                'store-stock' => false,
                'create-stock' => false,
                'edit-stock' => false,
                'show-stock' => false,
                'destroy-stock' => false,
                'index-stock' => false,
                'update-stock' => false,

                'store-address' => true,
                'show-address' => true,
                'destroy-address' => true,
                'index-address' => true,
                'update-address' => true,
                'edit-address' => true,
                'create-address' => true,

                'store-user_order' => true,
                'show-user_order' => true,
                'edit-user_order' => true,
                'create-user_order' => true,
                'index-user_order' => true,
                'update-user_order' => true,
                'destroy-user_order' => false,

                'store-order' => false,
                'create-order' => false,
                'edit-order' => false,
                'show-order' => false,
                'destroy-order' => false,
                'index-order' => false,
                'update-order' => false,

                'store-post' => false,
                'index-post' => true,
                'create-post' => false,
                'edit-post' => false,
                'show-post' => true,
                'update-post' => false,
                'destroy-post' => false,
                'approve-post' => false,

                'store-location' => false,
                'create-location' => false,
                'edit-location' => false,
                'index-location' => true,
                'show-location' => true,
                'update-location' => false,
                'destroy-location' => false,

                'store-product' => false,
                'create-product' => false,
                'edit-product' => false,
                'index-product' => true,
                'show-product' => true,
                'update-product' => false,
                'destroy-product' => false,

                'index-product_variation' => true,
                'create-product_variation' => false,
                'edit-product_variation' => true,
                'show-product_variation' => false,
                'update-product_variation' => false,
                'store-product_variation' => false,
                'destroy-product_variation' => false,

                'index-product_variation_type' => false,
                'create-product_variation_type' => false,
                'edit-product_variation_type' => false,
                'show-product_variation_type' => false,
                'update-product_variation_type' => false,
                'store-product_variation_type' => false,
                'destroy-product_variation_type' => false,

                'store-category' => false,
                'edit-category' => false,
                'create-category' => false,
                'show-category' => true,
                'update-category' => false,
                'destroy-category' => false,

                'store-review' => true,
                'destroy-review' => true,
                'update-review' => true,

                'store-comment' => true,
                'update-comment' => true,
                'show-comment' => true,
                'destroy-comment' => true,

                'store-user' => false,
                'create-user' => false,
                'edit-user' => false,
                'show-user' => false,
                'destroy-user' => false,
                'index-user' => false,
                'update-user' => false,

                'index-notification' => true,
                'update-notification' => true,

            ],
        ]);
    }
}
